name: IPFS Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Build
        run: |
          corepack enable
          yarn set version stable
          yarn install
          yarn build
      - name: Deploy to IPFS using Pinata
        env:
          PINATA_TOKEN: ${{ secrets.PINATA_TOKEN }}
        run: |
          node scripts/pinata-upload.js
      - name: Commit CID
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(action): update cid"
          file_pattern: 'cid.txt'
