name: IPFS Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Build
        run: |
          yarn install
          yarn build
      - id: deploy
        name: Deploy to IPFS using Pinata
        run: |
          CID=$(node scripts/pinata-upload.js | tail -n 1)
          echo "cid=$CID" >> $GITHUB_OUTPUT
      - name: Write CID
        run: |
          echo "${{steps.deploy.outputs.cid}}" > cid.txt
      - name: Commit CID
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(action): update cid"
          file_pattern: 'cid.txt'
