name: IPFS Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Build
        run: |
          yarn install
          yarn build
      - name: Update packages
        run: |
          sudo apt update
      - name: Install ipfs
        run: |
          ./.github/scripts/install-ipfs.sh
      - name: Initialize ipfs
        run: |
          ipfs init
      - name: Launch ipfs daemon
        run: |
          ipfs daemon &
      - name: Wait 20 seconds for daemon to launch
        run: |
          sleep 20
      - id: deploy
        name: Deploy build to ipfs
        run: |
          CID=$(ipfs add -r --quiet ./dist | tail -n 1)
          echo "cid=$CID" >> $GITHUB_OUTPUT
      - id: write
        name: Write CID
        run: |
          echo "${{steps.deploy.outputs.cid}}" > cid.txt
          git diff --exit-code || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit CID
        if: steps.write.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(auto): update cid"
          file_pattern: 'cid.txt'
